### ISSUE TITLE
Multiple inheritance crashes flask-sqlalchemy-stubs

### ISSUE THREAD

**Issue by bglogic** [ssfdust/flask-sqlalchemy-stubs#5]
Python 3.8

**Using mypy 0.782**

```powershell
(venv) PS C:\path\to\project> dmypy run -- --strict --follow-imports error .

Restarting: configuration changed
Daemon stopped
Daemon started
Daemon crashed!
Traceback (most recent call last):
  File "mypy\dmypy_server.py", line 223, in serve
  File "mypy\dmypy_server.py", line 266, in run_command
  File "mypy\dmypy_server.py", line 325, in cmd_run
  File "mypy\dmypy_server.py", line 382, in check
  File "mypy\dmypy_server.py", line 412, in initialize_fine_grained
  File "mypy\build.py", line 180, in build
  File "mypy\build.py", line 252, in _build
  File "mypy\build.py", line 2626, in dispatch
  File "mypy\build.py", line 2949, in process_graph
  File "mypy\build.py", line 3041, in process_stale_scc
  File "mypy\semanal_main.py", line 78, in semantic_analysis_for_scc
  File "mypy\semanal_main.py", line 199, in process_top_levels
  File "mypy\semanal_main.py", line 326, in semantic_analyze_target
  File "mypy\semanal.py", line 357, in refresh_partial
  File "mypy\semanal.py", line 368, in refresh_top_level
  File "mypy\semanal.py", line 4693, in accept
  File "mypy\errors.py", line 720, in report_internal_error
  File "mypy\semanal.py", line 4691, in accept
  File "mypy\nodes.py", line 939, in accept
  File "mypy\semanal.py", line 1011, in visit_class_def
  File "mypy\semanal.py", line 1088, in analyze_class
  File "mypy\semanal.py", line 1097, in analyze_class_body_common
  File "mypy\semanal.py", line 1157, in apply_class_plugin_hooks
  File "c:\path\to\project\venv\lib\site-packages\flasksqlamypy\hooks.py", line 72, in model_base_class_hook
    add_query_to_cls(ctx)
  File "c:\path\to\project\venv\lib\site-packages\flasksqlamypy\utils.py", line 332, in add_query_to_cls
    query_type = get_query_class_from_base(ctx)
  File "c:\path\to\project\venv\lib\site-packages\flasksqlamypy\utils.py", line 313, in get_query_class_from_base
    if "query_class" in expr.node.names:  # type: ignore
AttributeError: 'Var' object has no attribute 'names'
```

**Using mypy 0.790**

```powershell
(venv) PS C:\path\to\project> dmypy run -- --strict --follow-imports error .

Daemon crashed!
Traceback (most recent call last):
  File "mypy\dmypy_server.py", line 221, in serve
  File "mypy\dmypy_server.py", line 264, in run_command
  File "mypy\dmypy_server.py", line 323, in cmd_run
  File "mypy\dmypy_server.py", line 383, in check
  File "mypy\dmypy_server.py", line 511, in fine_grained_increment  
  File "mypy\server\update.py", line 243, in update
  File "mypy\server\update.py", line 309, in update_one
  File "mypy\server\update.py", line 374, in update_module
  File "mypy\server\update.py", line 590, in update_module_isolated 
  File "mypy\semanal_main.py", line 78, in semantic_analysis_for_scc
  File "mypy\semanal_main.py", line 199, in process_top_levels
  File "mypy\semanal_main.py", line 326, in semantic_analyze_target
  File "mypy\semanal.py", line 357, in refresh_partial
  File "mypy\semanal.py", line 368, in refresh_top_level
  File "mypy\semanal.py", line 4702, in accept
  File "mypy\errors.py", line 741, in report_internal_error
  File "mypy\semanal.py", line 4700, in accept
  File "mypy\nodes.py", line 1196, in accept
  File "mypy\semanal.py", line 3255, in visit_if_stmt
  File "mypy\semanal.py", line 3170, in visit_block
  File "mypy\semanal.py", line 4702, in accept
  File "mypy\errors.py", line 741, in report_internal_error
  File "mypy\semanal.py", line 4700, in accept
  File "mypy\nodes.py", line 1063, in accept
  File "mypy\semanal.py", line 1943, in visit_assignment_stmt
  File "mypy\semanal.py", line 2194, in apply_dynamic_class_hook
  File "c:\path\to\project\venv\lib\site-packages\flasksqlamypy\hooks.py", line 38, in declarative_base_hook
    info = create_dynamic_class(
  File "c:\path\to\project\venv\lib\site-packages\flasksqlamypy\utils.py", line 204, in create_dynamic_class
    add_query_cls_var(ctx.api, info)
  File "c:\path\to\project\venv\lib\site-packages\flasksqlamypy\utils.py", line 145, in add_query_cls_var
    assert sym is not None
AssertionError
```

**Comment by ssfdust** [comment]
Could you provide the example you check?
I guess there could be some model defined with custom __init__.

**Comment by smmalmansoori** [comment]
No custom `__init__` but multiple inheritance, it doesn't seem to be the cause of the crash though:

```python
class CoreMixin:
    id = db.Column(db.Integer(), primary_key=True)
    at_created = db.Column(db.DateTime(), nullable=False, default=datetime.utcnow)
    at_modified = db.Column(db.DateTime(), nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)


class Category(CoreMixin, BaseModel):
    name = db.Column(db.String(32), nullable=False, index=True, unique=True)
```

When running `dmypy` it crashes without reporting the line number from my code. However, running `mypy` (no daemon) it shows the following error:

```
.\app\model\models.py:128: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
If this issue continues with mypy master, please report a bug at https://github.com/python/mypy/issues
version: 0.790
```

So the offending section is the `User` model which inherits `UserMixin` (from Flask-Login):

```python
class User(CoreMixin, UserMixin, BaseModel):  # <- Line causing the crash according to mypy
    username = db.Column(db.String(30), nullable=False, index=True, unique=True)
    password = db.Column(PasswordType(), nullable=False)
    ...
```

**Comment by smmalmansoori** [comment]
Here is a minimal example that reproduces the issue

`sqlflask_stub_test/sample.py`
```python
from datetime import datetime
from typing import TYPE_CHECKING

from flask import Flask

from flask_login import LoginManager, UserMixin

from flask_sqlalchemy import SQLAlchemy

from sqlalchemy import MetaData


app = Flask(__name__)
app.config['SECRET_KEY'] = 'this-is-a-secret'
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite://'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
login = LoginManager(app)
db = SQLAlchemy(app)

if TYPE_CHECKING:
    from flask_sqlalchemy.model import Model

    BaseModel = db.make_declarative_base(Model)
else:
    BaseModel = db.Model


class CoreMixin:
    id = db.Column(db.Integer(), primary_key=True)
    at_created = db.Column(db.DateTime(), nullable=False, default=datetime.utcnow)
    at_modified = db.Column(db.DateTime(), nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)


class Category(CoreMixin, BaseModel):
    name = db.Column(db.String(32), nullable=False, index=True, unique=True)


class User(CoreMixin, UserMixin, BaseModel):
    username = db.Column(db.String(30), nullable=False, index=True, unique=True)
    email = db.Column(db.String(255), nullable=False, index=True, unique=True)
    password = db.Column(db.String(255), nullable=False)


@login.user_loader
def load_user(id: 'str') -> 'User':
    return User.query.get(int(id))


@app.route('/')
def hello_world():
    return 'Hello, World!'


if __name__ == '__main__':
    app.run(debug=True)

```

`sqlflask_stub_test/mypy.ini`
```ini
[mypy]
follow_imports = error
plugins = sqlmypy, flasksqlamypy
```

Dependencies
```powershell
pip install git+https://github.com/ssfdust/flask-sqlalchemy-stubs.git
pip install flask-login
```

Run in root directory using `dmypy`
```powershell
dmypy run -- --strict .
```

Run in root directory using `mypy`
```powershell
mypy --strict .
```

**Comment by ssfdust** [comment]
Sorry for slow response, I am busy these days.

Try to install the fixing version via
`pip install git+https://github.com/ssfdust/flask-sqlalchemy-stubs.git@dc89cdad95d154fe18854414449ae2f73dfd09d5 --upgrade`

Any feed is welcome.

**Comment by smmalmansoori** [comment]
It's working great! Thank you for putting the time into this.
